spring:
  application:
    name: request-processor
  datasource:
    url: jdbc:postgresql://localhost:5434/request_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

outbox:
  batch-size: 50
  delay-ms: 1000
